### PR TITLE
Alias fix

### PR DESCRIPTION
**Pull request by ehatch90**
This fixed the alias bug for us that we were experiencing with Issue #51 . This should add the group by tags to each series (and not extra ones) except when using the reserved tags found in the code i.e. $group_by(, _tag_group_, _time_group_, and _value_group_. This behavior was appropriate for our use case and I thought you might be able to use the code, even if it isn't exactly what you wanted. The changes can be found in datasource.js.

Let me know if there is another change you would prefer and I might be able to work it more to your liking.

### CODE REVIEW

**Comment by danielkza** [comment]
Any change to get this fix in? It makes working with graphs with many tag groups much more painful than it should be. Properly tagging each series seems like a really basic feature.

**Comment by yenaworld** [comment]
Even if it does not solve the problem, you can solve the problem easily.
https://yenaworldblog.wordpress.com/2017/11/06/grafana-kairosdb-plugin/

**Comment by danielkza** [comment]
@yenaworld Unfortunately I cannot read Korean. Any chance you can make a PR with the fix?

**Comment by jifwin** [comment]
This has completely refactored in v3.0.0.

**Pull request closed without merging**
